### ISSUE TITLE
/kafka-webui/src/main/scala/com/arturmkrtchyan/kafka/webui/zk/ZkUtil.scala:45: type mismatch

### ISSUE THREAD

**Issue by pavan538** [arturmkrtchyan/kafka-webui#1]
I am getting the following error, when i tried to run the container:start

[info] Generating /Users/pavan.t/kafka-webui/target/scala-2.11/resource_managed/main/rebel.xml.
[info] Compiling Templates in Template Directory: /Users/pavan.t/kafka-webui/src/main/webapp/WEB-INF/templates
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[info] Compiling 6 Scala sources to /Users/pavan.t/kafka-webui/target/scala-2.11/classes...
[error] /Users/pavan.t/kafka-webui/src/main/scala/com/arturmkrtchyan/kafka/webui/zk/ZkUtil.scala:45: type mismatch;
[error]  found   : Array[Byte]
[error]  required: String
[error]     val dataStr: String = curator.getData.storingStatIn(stat).forPath(path)
[error]                                                                      ^
[error] one error found
[error] (compile:compile) Compilation failed
[error] Total time: 4 s, completed 10 Jun, 2015 6:03:14 PM

**Comment by arturmkrtchyan** [comment]
@pavan538 I will look into this. But just FYI this project is not really ready to be used. it's Work in Progress.

**Comment by arturmkrtchyan** [comment]
@pavan538 it's fixed now. Fixes @1
